### ISSUE TITLE
Error While installing graphicsmagick

### ISSUE THREAD

**Issue by JeanPierreFig** [ungoldman/hi8#7]
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/t/tiff/tiff_4.

curl: (22) The requested URL returned error: 404 Not Found

**Comment by ungoldman** [comment]
Hi @JeanPierreFig! This looks like an error with how you're installing graphicsmagick, which I have no control over. I tried installing graphicsmagick locally using the recommended method in the readme (`brew install graphicsmagick`) and encountered no problems. If you're encountering a 404, the server in question might have been temporarily unavailable, or you might be behind a firewall. I'd suggest trying again, and if you keep encountering problems you can try reading through the graphicsmagick site (http://www.graphicsmagick.org) or seeing if there are similar solved issues on stackoverflow (for example, https://stackoverflow.com/questions/33786512/install-imagemagick-graphicsmagick-fail). Best of luck!
